version: "3"

services:
  jenkins:
    privileged: true
    build: .
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/my_marvin.yml
      - USER_CHOCOLATEEN_PASSWORD=chocolatine
      - USER_VAUGIE_G_PASSWORD=chocolatine
      - USER_I_DONT_KNOW_PASSWORD=chocolatine
      - USER_NASSO_PASSWORD=chocolatine
    ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - ./my_marvin.yml:/var/jenkins_home/casc_configs/my_marvin.yml
